---
deployment:
  tasks:
    - source /home/zamuaker/virtualenv/api/3.12/bin/activate && cd /home/zamuaker/api
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
