# Generated by Django 4.1.13 on 2025-07-07 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gateway Name')),
                ('is_active', models.BooleanField(default=True)),
                ('credentials', models.JSONField(blank=True, null=True, verbose_name='Credentials')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_to', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Transaction Reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Gateway Response')),
                ('result_type', models.BooleanField(blank=True, null=True, verbose_name='Result Type')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('gateway_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gateway Amount')),
                ('gateway_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash from Gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.paymentgateway')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
