# Generated by Django 4.1.13 on 2025-07-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_paymenttransaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
