# Generated by Django 4.1.13 on 2025-07-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
