# Generated by Django 4.1.13 on 2025-07-07 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_serviceprovider_menu_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorinstitutionvendor',
            name='companyLogo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='sponsorinstitutionvendor',
            name='orgRep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sponsorinstitutionvendor',
            name='partnershipInterest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
