# Generated by Django 4.1.13 on 2025-07-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_sponsorinstitutionvendor_companylogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='retail_wholesale',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('product', 'Product Vendor'), ('service', 'Service Provider'), ('sponsor', 'Sponsor/Institution Vendor')], max_length=20),
        ),
    ]
