# Generated by Django 4.1.13 on 2025-07-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_business_category_vendor_retail_wholesale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvendor',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
