# Generated by Django 4.1.13 on 2025-07-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_productvendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorinstitutionvendor',
            name='status',
            field=models.CharField(default='ON_PROCESSING', max_length=50),
        ),
    ]
