# Generated by Django 4.1.13 on 2025-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client Adress'),
        ),
    ]
